/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.esic.ihm;

import de.esic.dao.ConnexionBd;
import fr.esic.proprities.PropriGlobal;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class Commencer_Sport extends javax.swing.JFrame {

    static int milliseconde = 0;
    static int seconde = 0;
    static int minute = 0;
    static int heure = 0;
    static boolean state = true;
    //static String Tmps;
    
    int nbre_heure;
    String activite;
     PreparedStatement prepare;
            Statement st;
            ResultSet rst;
             Timer t;
    int time=0;
    public Commencer_Sport() {
        initComponents();
          setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_start = new javax.swing.JButton();
        Time_sport = new javax.swing.JLabel();
        txt_hour = new javax.swing.JLabel();
        txt_minute = new javax.swing.JLabel();
        txt_seconde = new javax.swing.JLabel();
        txt_milliseconde = new javax.swing.JLabel();
        btn_stop = new javax.swing.JButton();
        btn_valider_temps = new javax.swing.JButton();
        lb_msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_start.setBackground(new java.awt.Color(204, 204, 255));
        btn_start.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        btn_start.setForeground(new java.awt.Color(0, 102, 0));
        btn_start.setText("Start!");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        getContentPane().add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 110, 40));
        getContentPane().add(Time_sport, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        txt_hour.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        txt_hour.setForeground(new java.awt.Color(255, 153, 0));
        txt_hour.setText("00:");
        getContentPane().add(txt_hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 60, 60));

        txt_minute.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        txt_minute.setForeground(new java.awt.Color(255, 153, 0));
        txt_minute.setText("00:");
        getContentPane().add(txt_minute, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 60, 60));

        txt_seconde.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        txt_seconde.setForeground(new java.awt.Color(255, 153, 0));
        txt_seconde.setText("00:");
        getContentPane().add(txt_seconde, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 60, 60));

        txt_milliseconde.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        txt_milliseconde.setForeground(new java.awt.Color(255, 153, 0));
        txt_milliseconde.setText("00");
        getContentPane().add(txt_milliseconde, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 80, 60));

        btn_stop.setBackground(new java.awt.Color(204, 204, 255));
        btn_stop.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        btn_stop.setForeground(new java.awt.Color(204, 0, 14));
        btn_stop.setText("Stop!");
        btn_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stopActionPerformed(evt);
            }
        });
        getContentPane().add(btn_stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 110, 40));

        btn_valider_temps.setBackground(new java.awt.Color(204, 204, 255));
        btn_valider_temps.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        btn_valider_temps.setForeground(new java.awt.Color(0, 0, 153));
        btn_valider_temps.setText("Valider ");
        btn_valider_temps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_valider_tempsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_valider_temps, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 210, 40));

        lb_msg.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        getContentPane().add(lb_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 390, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
 
        
         t =new Timer(10,new ActionListener() {
         public void actionPerformed(ActionEvent e) {
       txt_milliseconde.setText(String.valueOf(time));
       
        
       time= time+10;
       heure=time/3600000;
       minute=(time/60000)%60;
       seconde=(time/1000)%60;
       txt_seconde.setText(""+seconde);
       txt_minute.setText(""+minute);
       txt_hour.setText(""+heure);
        
        
         
    } 
}); 
        t.start();
                           if(milliseconde>100)
                            {
                                milliseconde=0;
                                seconde++;
                                
                            }
                            
                            if(seconde>60)
                            {
                                milliseconde=0;
                                seconde=0;
                                minute++;
                            }
                            
                            
                            if(minute>60)
                            {
                                milliseconde=0;
                                seconde=0;
                                minute=0;
                                heure++;
                                
                            }
                           
                            
                             txt_milliseconde.setText(" : "+milliseconde);
                        milliseconde++;
                        
                        txt_seconde.setText(" : "+seconde+" s ");
                        txt_minute.setText(" : "+minute +" min ");
                        txt_hour.setText(""+heure+" H " );
//state = true;
       
        
          lb_msg.setVisible(true);
        lb_msg.setText("BON COURGE !!!");
        lb_msg.setForeground(Color.green);
        /*
    Thread t = new Thread() 
        {
            public void run ()
                    
            {
                
                for (; ; )
                {
                    if(state==true)
                    {
                        try
                        {
                            sleep(1);
                            if(milliseconde>1000)
                            {
                                milliseconde=0;
                                seconde++;
                                
                            }
                            
                            if(seconde>60)
                            {
                                milliseconde=0;
                                seconde=0;
                                minute++;
                            }
                            
                            
                            if(minute>60)
                            {
                                milliseconde=0;
                                seconde=0;
                                minute=0;
                                heure++;
                                
                            }
                           
                            
                             txt_milliseconde.setText(" : "+milliseconde);
                        milliseconde++;
                        
                        txt_seconde.setText(" : "+seconde);
                        txt_minute.setText(" : "+minute);
                        txt_hour.setText(""+heure);
                           
                        } catch (Exception e)
                        {
                        }
                  
                    }
                    else{
                        break;
                    }
                    
                    
                }
                
            }
            
        };
    
    t.start();
    */
     btn_stop.setEnabled(true);
     btn_valider_temps.setEnabled(false);
      btn_start.setEnabled(false);
   
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stopActionPerformed
t.stop();
lb_msg.setVisible(true);
lb_msg.setText("Reposer ou Valider!!");
lb_msg.setForeground(Color.red);
state=false;
      
          // TODO add your handling code here:
      /*  lb_msg.setVisible(true);
lb_msg.setText("Essayez de nouveau !!!");
  lb_msg.setForeground(Color.blue);
        state=false;
          heure=0;
        milliseconde=0;
        minute=0;
        seconde=0;
        txt_hour.setText("00:");
        txt_minute.setText("00:");
        txt_seconde.setText("00:");
        txt_milliseconde.setText("00");*/
      
     
     
      btn_start.setEnabled(true);
      btn_valider_temps.setEnabled(true);
         btn_stop.setEnabled(false);
      // String  Time =txt_hour.getText()+"H"+txt_minute.getText()+"min" +txt_seconde.getText()+"s"; 
       
         System.out.println(""+time);
    }//GEN-LAST:event_btn_stopActionPerformed

    private void btn_valider_tempsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_valider_tempsActionPerformed

  
         String sql = "insert into regime_perdre_poids (nbre_heure) values(?)";
        try {
            Connection connexion=ConnexionBd.getConnection();
            PreparedStatement prepare;
        
            prepare = connexion.prepareCall(sql);
            prepare.setInt(1, time);
            
        prepare.execute(); 
        } catch (Exception e) {
        }
        
        
        int response=JOptionPane.showConfirmDialog(this, "Vous voullez vraimant Enregistre et quitter?", "Quitter KorParfait ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       
        if (response==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(rootPane, "Enregistrment avec succces");
            this.dispose();
            System.out.println("vous avez quitté l'application");
        } 

        else if (response==JOptionPane.NO_OPTION){

            System.out.println("vous avez resté dans  l'application");
        }

        else if (response==JOptionPane.CLOSED_OPTION)

        {System.out.println("fenetre fermée!");}       
        
        
        

// TODO add your handling code here:
      /*  lb_msg.setVisible(true);
lb_msg.setText("Essayez de nouveau !!!");
  lb_msg.setForeground(Color.blue);
        state=false;
          heure=0;
        milliseconde=0;
        minute=0;
        seconde=0;
        txt_hour.setText("00:");
        txt_minute.setText("00:");
        txt_seconde.setText("00:");
        txt_milliseconde.setText("00");
        */
     
    }//GEN-LAST:event_btn_valider_tempsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lb_msg.hide();
        btn_valider_temps.setEnabled(false);
        btn_stop.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commencer_Sport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commencer_Sport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commencer_Sport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commencer_Sport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Commencer_Sport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Time_sport;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_stop;
    private javax.swing.JButton btn_valider_temps;
    private javax.swing.JLabel lb_msg;
    private javax.swing.JLabel txt_hour;
    private javax.swing.JLabel txt_milliseconde;
    private javax.swing.JLabel txt_minute;
    private javax.swing.JLabel txt_seconde;
    // End of variables declaration//GEN-END:variables
}
