/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.esic.ihm;

import de.esic.dao.ConnexionBd;
import de.esic.dao.UserDao;
import fr.esic.model.User;
import fr.esic.proprities.PropriGlobal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Nathan Ghozlan
 */
public class Completer_Profile extends javax.swing.JFrame {

    /**
     * Creates new form Completer_Profile
     */
    public Completer_Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMsgAccueil = new javax.swing.JLabel();
        lbMail = new javax.swing.JLabel();
        lbEtudes = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        txtEtudes = new javax.swing.JTextField();
        btValider = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();
        lb_msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbMsgAccueil.setBackground(new java.awt.Color(102, 102, 255));
        lbMsgAccueil.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbMsgAccueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbMail.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbMail.setText("eMail");

        lbEtudes.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbEtudes.setText("Etudes");

        txtMail.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N

        txtEtudes.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N

        btValider.setBackground(new java.awt.Color(0, 153, 0));
        btValider.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btValider.setForeground(new java.awt.Color(255, 255, 255));
        btValider.setText("Valider les modifications");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });

        btRetour.setBackground(new java.awt.Color(255, 255, 0));
        btRetour.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btRetour.setForeground(new java.awt.Color(255, 51, 51));
        btRetour.setText("Retour sur mon profil");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbEtudes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(txtEtudes, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(btValider)
                .addGap(156, 156, 156)
                .addComponent(btRetour)
                .addGap(75, 75, 75))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(204, 204, 204)
                            .addComponent(lbMsgAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbMail, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(143, 143, 143)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(lb_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEtudes)
                    .addComponent(txtEtudes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btValider)
                    .addComponent(btRetour))
                .addGap(106, 106, 106))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 39, Short.MAX_VALUE)
                    .addComponent(lbMsgAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(lbMail))
                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(143, 143, 143)
                    .addComponent(lb_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 160, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        // TODO add your handling code here:

        String login = PropriGlobal.user_Connect.getLogin();
        String password = PropriGlobal.user_Connect.getPassword();

        String mail = txtMail.getText();
        String etudes = txtEtudes.getText();

        String sql = "UPDATE sportif SET mail = ? , etudes= ? WHERE id = ?";

        //System.out.println(sql);
        try {

            Connection connexion = ConnexionBd.getConnection();
            PreparedStatement prepare;
            prepare = connexion.prepareStatement(sql);
            prepare.setString(1, mail);
            prepare.setString(2, etudes);
            prepare.setInt(3, PropriGlobal.user_Connect.getId());

            prepare.execute();

            User u = UserDao.getByLoginAndPassword(login, password);

            if (u != null) {
                JOptionPane.showMessageDialog(rootPane, "mise à jour du profile reussies!");
                Fenetre_de_demarage demarage = new Fenetre_de_demarage();
                demarage.setVisible(true);
                this.setVisible(false);
            } else {
                lb_msg.setVisible(true);
                lb_msg.setText("un ou plusieurs champs sont incorrectes!! ");
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "exception!" + e.getMessage());
        }
    }//GEN-LAST:event_btValiderActionPerformed

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        // TODO add your handling code here:
        Fenetre_de_demarage profil = new Fenetre_de_demarage();
        profil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Completer_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Completer_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Completer_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Completer_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Completer_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRetour;
    private javax.swing.JButton btValider;
    private javax.swing.JLabel lbEtudes;
    private javax.swing.JLabel lbMail;
    private javax.swing.JLabel lbMsgAccueil;
    private javax.swing.JLabel lb_msg;
    private javax.swing.JTextField txtEtudes;
    private javax.swing.JTextField txtMail;
    // End of variables declaration//GEN-END:variables
}
