/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.esic.ihm;

import de.esic.dao.ConnexionBd;
import de.esic.dao.UserDao;
import fr.esic.model.User;
import fr.esic.proprities.PropriGlobal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Nathan Ghozlan
 */
public class Modifier_Profile extends javax.swing.JFrame {

    /**
     * Creates new form Modifier_Profile
     */
    public Modifier_Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMsgBonjour = new javax.swing.JLabel();
        lbNewLog = new javax.swing.JLabel();
        lbNewMdp = new javax.swing.JLabel();
        lbNewPoids = new javax.swing.JLabel();
        txtNewLog = new javax.swing.JTextField();
        txtNewPoids = new javax.swing.JTextField();
        btValider = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();
        lb_msg = new javax.swing.JLabel();
        txtNewMdp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMsgBonjour.setBackground(new java.awt.Color(102, 102, 255));
        lbMsgBonjour.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbMsgBonjour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbMsgBonjour, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 16, 346, 46));

        lbNewLog.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbNewLog.setText("Nouveau login");
        getContentPane().add(lbNewLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, 151, -1));

        lbNewMdp.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbNewMdp.setText("Nouveau mdp");
        getContentPane().add(lbNewMdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 142, 151, -1));

        lbNewPoids.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbNewPoids.setText("Nouveau poids");
        getContentPane().add(lbNewPoids, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 204, 151, -1));

        txtNewLog.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        getContentPane().add(txtNewLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 99, 196, -1));

        txtNewPoids.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        getContentPane().add(txtNewPoids, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 201, 196, -1));

        btValider.setBackground(new java.awt.Color(0, 153, 0));
        btValider.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btValider.setForeground(new java.awt.Color(255, 255, 255));
        btValider.setText("Valider les modifications");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });
        getContentPane().add(btValider, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 334, -1, -1));

        btRetour.setBackground(new java.awt.Color(255, 255, 0));
        btRetour.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btRetour.setForeground(new java.awt.Color(255, 51, 51));
        btRetour.setText("Retour sur mon profil");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });
        getContentPane().add(btRetour, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 334, -1, -1));
        getContentPane().add(lb_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 274, 602, 42));

        txtNewMdp.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        getContentPane().add(txtNewMdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 139, 196, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lbMsgBonjour.setText("ici modifiez votre profil " + PropriGlobal.user_Connect.getPrenom());
    }//GEN-LAST:event_formWindowOpened

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        // TODO add your handling code here:
        Fenetre_de_demarage profil = new Fenetre_de_demarage();
        profil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRetourActionPerformed

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        // TODO add your handling code here:

        String lastLogin = PropriGlobal.user_Connect.getLogin();
        System.out.println(lastLogin);
        String login = txtNewLog.getText();
        String password = txtNewMdp.getText();
        int poids = Integer.parseInt(txtNewPoids.getText());

        
        String sql = "UPDATE sportif SET login = ? , mdp= ?, mdp2= ?, poids= ? WHERE id = ?";

        //System.out.println(sql);
        
        try {

            Connection connexion = ConnexionBd.getConnection();
            PreparedStatement prepare;
            prepare = connexion.prepareStatement(sql);
            prepare.setString(1, login);
            prepare.setString(2, password);
            prepare.setString(3, password);
            prepare.setInt(4, poids);
            prepare.setInt(5, PropriGlobal.user_Connect.getId());

            prepare.execute();

            User u = UserDao.getByLoginAndPassword(login, password);

            if (u != null) {
                JOptionPane.showMessageDialog(rootPane, "modifications reussies!");
                Fenetre_de_demarage demarage = new Fenetre_de_demarage();
                demarage.setVisible(true);
                this.setVisible(false);
            } else {
                lb_msg.setVisible(true);
                lb_msg.setText("identifiant ou mot de passe incorrecte!! ");
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "exception!" + e.getMessage());
        }

    }//GEN-LAST:event_btValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifier_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifier_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifier_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifier_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifier_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRetour;
    private javax.swing.JButton btValider;
    private javax.swing.JLabel lbMsgBonjour;
    private javax.swing.JLabel lbNewLog;
    private javax.swing.JLabel lbNewMdp;
    private javax.swing.JLabel lbNewPoids;
    private javax.swing.JLabel lb_msg;
    private javax.swing.JTextField txtNewLog;
    private javax.swing.JPasswordField txtNewMdp;
    private javax.swing.JTextField txtNewPoids;
    // End of variables declaration//GEN-END:variables
}
