/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.esic.ihm;

import de.esic.dao.ConnexionBd;
import de.esic.dao.UserDao;
import fr.esic.model.User;
import fr.esic.proprities.PropriGlobal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Nathan Ghozlan
 */
public class Modifier_Profile extends javax.swing.JFrame {

    /**
     * Creates new form Modifier_Profile
     */
    public Modifier_Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMsgBonjour = new javax.swing.JLabel();
        lbNewLog = new javax.swing.JLabel();
        lbNewMdp = new javax.swing.JLabel();
        lbNewPoids = new javax.swing.JLabel();
        txtNewLog = new javax.swing.JTextField();
        txtNewPoids = new javax.swing.JTextField();
        btValider = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();
        lb_msg = new javax.swing.JLabel();
        txtNewMdp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbMsgBonjour.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lbMsgBonjour.setForeground(new java.awt.Color(255, 255, 255));
        lbMsgBonjour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMsgBonjour.setText("Bonjour");

        lbNewLog.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbNewLog.setText("Nouveau login");

        lbNewMdp.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbNewMdp.setText("Nouveau mdp");

        lbNewPoids.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbNewPoids.setText("Nouveau poids");

        btValider.setBackground(new java.awt.Color(0, 153, 0));
        btValider.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btValider.setForeground(new java.awt.Color(255, 255, 255));
        btValider.setText("Valider les modifications");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });

        btRetour.setBackground(new java.awt.Color(255, 255, 0));
        btRetour.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btRetour.setForeground(new java.awt.Color(255, 51, 51));
        btRetour.setText("Retour sur mon profil");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNewLog, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNewPoids, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNewMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNewPoids, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(txtNewLog)
                            .addComponent(lbMsgBonjour, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewMdp)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btValider)
                        .addGap(154, 154, 154)
                        .addComponent(btRetour)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMsgBonjour, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewLog)
                    .addComponent(txtNewLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewMdp)
                    .addComponent(txtNewMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewPoids)
                    .addComponent(txtNewPoids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(lb_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btValider)
                    .addComponent(btRetour))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lbMsgBonjour.setText("Bonjour " + PropriGlobal.user_Connect.getLogin());
    }//GEN-LAST:event_formWindowOpened

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        // TODO add your handling code here:
        Fenetre_de_demarage profil = new Fenetre_de_demarage();
        profil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRetourActionPerformed

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        // TODO add your handling code here:

        String login = txtNewLog.getText();
        String password = txtNewMdp.getText();
        int poids = Integer.parseInt(txtNewPoids.getText());

        String sql = "UPDATE sportif SET login = ? , mdp= ?, mdp2= ?, poids= ? WHERE id = ?";

        //System.out.println(sql);

        try {

            Connection connexion = ConnexionBd.getConnection();
            PreparedStatement prepare;
            prepare = connexion.prepareStatement(sql);
            prepare.setString(1, login);
            prepare.setString(2, password);
            prepare.setString(3, password);
            prepare.setInt(4, poids);
            prepare.setInt(5, PropriGlobal.user_Connect.getId());

            prepare.execute();

            User u = UserDao.getByLoginAndPassword(login, password);

            if (u != null) {
                JOptionPane.showMessageDialog(rootPane, "modifications reussies!");
                Fenetre_de_demarage demarage = new Fenetre_de_demarage();
                demarage.setVisible(true);
                this.setVisible(false);
            } else {
                lb_msg.setVisible(true);
                lb_msg.setText("idenifiant ou mot de passe incorrecte!! ");
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "exception!" + e.getMessage());
        }

    }//GEN-LAST:event_btValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifier_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifier_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifier_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifier_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifier_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRetour;
    private javax.swing.JButton btValider;
    private javax.swing.JLabel lbMsgBonjour;
    private javax.swing.JLabel lbNewLog;
    private javax.swing.JLabel lbNewMdp;
    private javax.swing.JLabel lbNewPoids;
    private javax.swing.JLabel lb_msg;
    private javax.swing.JTextField txtNewLog;
    private javax.swing.JPasswordField txtNewMdp;
    private javax.swing.JTextField txtNewPoids;
    // End of variables declaration//GEN-END:variables
}
