/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.esic.ihm;

import de.esic.dao.ConnexionBd;
import de.esic.dao.UserDao;
import fr.esic.model.User;
import fr.esic.proprities.PropriGlobal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nathan Ghozlan
 */
public class VoirMonProfil extends javax.swing.JFrame {

    /**
     * Creates new form Completer_Profile
     */
    public VoirMonProfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMsgAccueil = new javax.swing.JLabel();
        btRetour = new javax.swing.JButton();
        lbPoids = new javax.swing.JLabel();
        lbTaille = new javax.swing.JLabel();
        lb_msg = new javax.swing.JLabel();
        btn_modifie_profil = new javax.swing.JButton();
        lbPass = new javax.swing.JLabel();
        lbPoidsCont = new javax.swing.JLabel();
        lbPrenom = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();
        lbSexe1 = new javax.swing.JLabel();
        lbNom = new javax.swing.JLabel();
        lbPassCont = new javax.swing.JLabel();
        btMdpCont = new javax.swing.JButton();
        lbLoginCont = new javax.swing.JLabel();
        lbNomCont = new javax.swing.JLabel();
        lbPrenomCont = new javax.swing.JLabel();
        lbSexeCont = new javax.swing.JLabel();
        lbAge = new javax.swing.JLabel();
        lbAgeCont = new javax.swing.JLabel();
        lbTailleCont = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbMsgAccueil.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbMsgAccueil.setForeground(new java.awt.Color(0, 102, 204));
        lbMsgAccueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btRetour.setBackground(new java.awt.Color(255, 255, 0));
        btRetour.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btRetour.setForeground(new java.awt.Color(255, 51, 51));
        btRetour.setText("Retour sur mon profil");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });

        lbPoids.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbPoids.setText("Poids (Kg)");

        lbTaille.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbTaille.setText("Taille (cm)");

        lb_msg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_msg.setForeground(new java.awt.Color(204, 0, 51));

        btn_modifie_profil.setBackground(new java.awt.Color(153, 153, 153));
        btn_modifie_profil.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btn_modifie_profil.setForeground(new java.awt.Color(255, 255, 0));
        btn_modifie_profil.setText("Modifier le profil");
        btn_modifie_profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifie_profilActionPerformed(evt);
            }
        });

        lbPass.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbPass.setText("Password");

        lbPoidsCont.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N

        lbPrenom.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbPrenom.setText("Prenom");

        lbLogin.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbLogin.setText("Login");

        lbSexe1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbSexe1.setText("Sexe");

        lbNom.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbNom.setText("Nom");

        btMdpCont.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        btMdpCont.setText("Afficher mon mot de passe");
        btMdpCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMdpContActionPerformed(evt);
            }
        });

        lbNomCont.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N

        lbPrenomCont.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N

        lbSexeCont.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N

        lbAge.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbAge.setText("Age");

        lbAgeCont.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N

        lbTailleCont.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btn_modifie_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(btRetour))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbAge, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMsgAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNomCont, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPrenomCont, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSexeCont, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbLoginCont, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPassCont, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addComponent(btMdpCont, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTaille, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTailleCont, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNom, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSexe1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPoids, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAgeCont, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPoidsCont, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbPass, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMsgAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNomCont, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPrenomCont, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSexe1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSexeCont, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbLoginCont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPassCont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMdpCont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addComponent(lbAgeCont, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbAge, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPoids)
                        .addGap(18, 18, 18)
                        .addComponent(lbTaille)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPoidsCont, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_msg)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbTailleCont, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modifie_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ResultSet rst;

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lbMsgAccueil.setText("Mise à jour du profil de " + PropriGlobal.user_Connect.getLogin());

        //lbPassCont.setVisible(false);
        /*
        lbNomCont.setText(PropriGlobal.user_Connect.getNom());
        lbPrenomCont.setText(PropriGlobal.user_Connect.getPrenom());
        
        lbSexeCont.setText(PropriGlobal.user_Connect.getSex());
        lbAgeCont.setText(PropriGlobal.user_Connect.getAge() + " ans");
        lbLoginCont.setText(PropriGlobal.user_Connect.getLogin());
        lbPassCont.setText("*************");
        lbPoidsCont.setText(PropriGlobal.user_Connect.getPoids() + " Kg");
        lbTailleCont.setText(PropriGlobal.user_Connect.getTaille() + " cm");
         */
        String sql = "select * from sportif where id=" + PropriGlobal.user_Connect.getId();

        try {
            /*
            Connection connexion = ConnexionBd.getConnection();
            PreparedStatement prepare;
            prepare = connexion.prepareStatement(sql);
            lbTailleCont.setText(PropriGlobal.user_Connect.getTaille() + " cm");
            int taille = Integer.parseInt(lbTailleCont.getText());
            prepare.setInt(1, taille);
            prepare.execute();
             */
            
            Connection connexion = ConnexionBd.getConnection();

            Statement requete = connexion.createStatement();

            ResultSet rs = requete.executeQuery(sql);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "exception!" + e.getMessage());
        }


    }//GEN-LAST:event_formWindowOpened

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        // TODO add your handling code here:
        Fenetre_de_demarage profil = new Fenetre_de_demarage();
        profil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRetourActionPerformed

    private void btn_modifie_profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifie_profilActionPerformed
        // TODO add your handling code here:
        Modifier_Profile profil = new Modifier_Profile();
        profil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_modifie_profilActionPerformed

    private void btMdpContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMdpContActionPerformed
        // TODO add your handling code here:
        //lbPassCont.setText(PropriGlobal.user_Connect.getPassword());
        //btMdpCont.setVisible(false);
    }//GEN-LAST:event_btMdpContActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoirMonProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoirMonProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoirMonProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoirMonProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoirMonProfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMdpCont;
    private javax.swing.JButton btRetour;
    private javax.swing.JButton btn_modifie_profil;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbAgeCont;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbLoginCont;
    private javax.swing.JLabel lbMsgAccueil;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lbNomCont;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbPassCont;
    private javax.swing.JLabel lbPoids;
    private javax.swing.JLabel lbPoidsCont;
    private javax.swing.JLabel lbPrenom;
    private javax.swing.JLabel lbPrenomCont;
    private javax.swing.JLabel lbSexe1;
    private javax.swing.JLabel lbSexeCont;
    private javax.swing.JLabel lbTaille;
    private javax.swing.JLabel lbTailleCont;
    private javax.swing.JLabel lb_msg;
    // End of variables declaration//GEN-END:variables
}
