/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.esic.ihm;

import de.esic.dao.ConnexionBd;
import de.esic.dao.UserDao;
import fr.esic.model.User;
import fr.esic.proprities.PropriGlobal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nathan Ghozlan
 */
public class VoirMonProfil extends javax.swing.JFrame {

    static String sexe;

    /**
     * Creates new form Completer_Profile
     */
    public VoirMonProfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMsgAccueil = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btRetour = new javax.swing.JButton();
        lbPoids = new javax.swing.JLabel();
        lbTaille = new javax.swing.JLabel();
        lb_msg = new javax.swing.JLabel();
        btn_modifie_profil = new javax.swing.JButton();
        lbPass = new javax.swing.JLabel();
        lbPoidsCont = new javax.swing.JLabel();
        lbPrenom = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();
        lbSexe1 = new javax.swing.JLabel();
        lbNom = new javax.swing.JLabel();
        lbPassCont = new javax.swing.JLabel();
        btMdpCont = new javax.swing.JButton();
        lbLoginCont = new javax.swing.JLabel();
        lbNomCont = new javax.swing.JLabel();
        lbPrenomCont = new javax.swing.JLabel();
        lbSexeCont = new javax.swing.JLabel();
        lbAge = new javax.swing.JLabel();
        lbAgeCont = new javax.swing.JLabel();
        lbTailleCont = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMsgAccueil.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbMsgAccueil.setForeground(new java.awt.Color(0, 102, 204));
        lbMsgAccueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbMsgAccueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 346, 34));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(201, 22, 78));
        jLabel5.setText("Profil");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 100, 40));

        btRetour.setBackground(new java.awt.Color(255, 255, 0));
        btRetour.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btRetour.setForeground(new java.awt.Color(255, 51, 51));
        btRetour.setText("Retour");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });
        getContentPane().add(btRetour, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 180, 40));

        lbPoids.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbPoids.setText("Poids (Kg)");
        getContentPane().add(lbPoids, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 151, -1));

        lbTaille.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbTaille.setText("Taille (cm)");
        getContentPane().add(lbTaille, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 151, -1));

        lb_msg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_msg.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(lb_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 432, 447, -1));

        btn_modifie_profil.setBackground(new java.awt.Color(153, 153, 153));
        btn_modifie_profil.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btn_modifie_profil.setForeground(new java.awt.Color(255, 255, 0));
        btn_modifie_profil.setText("Modifier le profil");
        btn_modifie_profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifie_profilActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modifie_profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 473, 180, 40));

        lbPass.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbPass.setText("Password");
        getContentPane().add(lbPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 84, 34));

        lbPoidsCont.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        getContentPane().add(lbPoidsCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 123, 34));

        lbPrenom.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbPrenom.setText("Prenom");
        getContentPane().add(lbPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 68, 34));

        lbLogin.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbLogin.setText("Login");
        getContentPane().add(lbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 84, 34));

        lbSexe1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbSexe1.setText("Sexe");
        getContentPane().add(lbSexe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 68, 34));

        lbNom.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbNom.setText("Nom");
        getContentPane().add(lbNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 68, 34));
        getContentPane().add(lbPassCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 222, 125, 34));

        btMdpCont.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        btMdpCont.setText("Afficher mon mot de passe");
        btMdpCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMdpContActionPerformed(evt);
            }
        });
        getContentPane().add(btMdpCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 222, 168, 34));
        getContentPane().add(lbLoginCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 182, 125, 34));

        lbNomCont.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        getContentPane().add(lbNomCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 62, 125, 34));

        lbPrenomCont.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        getContentPane().add(lbPrenomCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 102, 125, 34));

        lbSexeCont.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        getContentPane().add(lbSexeCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 142, 125, 34));

        lbAge.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbAge.setText("Age");
        getContentPane().add(lbAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 84, 34));

        lbAgeCont.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        getContentPane().add(lbAgeCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 123, 34));

        lbTailleCont.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        getContentPane().add(lbTailleCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 123, 34));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/esic/img/cnx_img.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ResultSet rst;

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lbMsgAccueil.setText("Mise à jour du profil de " + PropriGlobal.user_Connect.getLogin());

        lbMsgAccueil.setText("Mise à jour du profil de " + PropriGlobal.user_Connect.getLogin());

        /*
        lbNomCont.setText(PropriGlobal.user_Connect.getNom());
        lbPrenomCont.setText(PropriGlobal.user_Connect.getPrenom());
        
        lbSexeCont.setText(PropriGlobal.user_Connect.getSex());
        //lbSexeCont.setText(sexe);
        lbAgeCont.setText(PropriGlobal.user_Connect.getAge() + " ans");
        lbLoginCont.setText(PropriGlobal.user_Connect.getLogin());
        lbPassCont.setText("*************");
        lbPoidsCont.setText(PropriGlobal.user_Connect.getPoids() + " Kg");
        lbTailleCont.setText(PropriGlobal.user_Connect.getTaille() + " cm");
        
         */
        //String sql = "select * from sportif where id= " + PropriGlobal.user_Connect.getId();
        try {

            /*
            Connection connexion = ConnexionBd.getConnection();
            PreparedStatement prepare;
            ResultSet rst;
            Statement st;
            st = connexion.createStatement();
            rst = st.executeQuery(sql);
            if (rst.next()){
                sexe= rst.getString("sex");
            }
            
             */
            Connection connexion = ConnexionBd.getConnection();

            Statement st = connexion.createStatement();
            ResultSet rs = st.executeQuery("select * from sportif where id= " + PropriGlobal.user_Connect.getId());
            while (rs.next()) {
                //System.out.print("Colonne 1 renvoy�e ");
                //System.out.println(rs.getString(4));
                lbSexeCont.setText(rs.getString(4));
                lbPassCont.setText("*************");
                lbTailleCont.setText(rs.getString(10));
                lbPoidsCont.setText(rs.getString(8));
                lbAgeCont.setText(rs.getString(9));
                lbLoginCont.setText(rs.getString(5));
                lbNomCont.setText(rs.getString(2));
                lbPrenomCont.setText(rs.getString(3));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "exception!" + e.getMessage());

        }

    }//GEN-LAST:event_formWindowOpened

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        // TODO add your handling code here:
        Fenetre_de_demarage profil = new Fenetre_de_demarage();
        profil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRetourActionPerformed

    private void btn_modifie_profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifie_profilActionPerformed
        // TODO add your handling code here:
        Modifier_Profile profil = new Modifier_Profile();
        profil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_modifie_profilActionPerformed

    private void btMdpContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMdpContActionPerformed
        // TODO add your handling code here:
        //lbPassCont.setText(PropriGlobal.user_Connect.getPassword());
        btMdpCont.setVisible(false);
        try {

            Connection connexion = ConnexionBd.getConnection();

            Statement st = connexion.createStatement();
            ResultSet rs = st.executeQuery("select * from sportif where id= " + PropriGlobal.user_Connect.getId());
            while (rs.next()) {

                lbPassCont.setText(rs.getString(6));

            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_btMdpContActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoirMonProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoirMonProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoirMonProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoirMonProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoirMonProfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMdpCont;
    private javax.swing.JButton btRetour;
    private javax.swing.JButton btn_modifie_profil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbAgeCont;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbLoginCont;
    private javax.swing.JLabel lbMsgAccueil;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lbNomCont;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbPassCont;
    private javax.swing.JLabel lbPoids;
    private javax.swing.JLabel lbPoidsCont;
    private javax.swing.JLabel lbPrenom;
    private javax.swing.JLabel lbPrenomCont;
    private javax.swing.JLabel lbSexe1;
    private javax.swing.JLabel lbSexeCont;
    private javax.swing.JLabel lbTaille;
    private javax.swing.JLabel lbTailleCont;
    private javax.swing.JLabel lb_msg;
    // End of variables declaration//GEN-END:variables
}
